### ISSUE TITLE
Seems to be broken sadly...

### ISSUE THREAD

**Issue by ghost** [random-geek/auroras#3]
I run mintest 5.4.0 with minetest_game and I get this: 
`
WARNING[Server]: Assignment to undeclared global "heightStrength" inside a function at ...st/5.4.0/minetest-5.4.0/bin/../mods/auroras/init.lua:227. `

I was in a cold biom with snow and used 
set_time = 1440 
in minetest.conf to speed up the time (it's one day and one night in 1 real time minute) and also used the default time setting before. 
I have never seen any auroras and I tested it several times. 

I always got that warning message about 20 o'clock (as in the description auroras are not visible at every night). 
A command to trigger them would be helpful to test if the mod works.

**Comment by random-geek** [comment]
Those warnings should be fixed now, and I've pushed another release to ContentDB.

As far as auroras not appearing, I tested the mod recently and everything seems to work fine. Note that even some snowy biomes are not cold enough for auroras. I would suggest making sure you are in a very cold place (like a permafrost biome), waiting for a few minutes, and walking around. If auroras still aren't showing up, you could try increasing the maximum heat value in settings.

I'll keep this issue open for now since it's probably a good idea to add some kind of command for testing.

**Comment by ghost** [comment]
Thank you very much, I will test the new release. 

Funny I was in a permafrost biom =) 
I also think that the warning message showed up because the auroras wanted to start there, waiting time was several days in mt and about an hour in real time.

**Comment by ghost** [comment]
Yay now it works in vanilla minetest. 
Great work @random-geek !
